### ISSUE TITLE
Error allocating memory

### ISSUE THREAD

**Issue by ggirelli** [gpertea/gffcompare#5] opened 2016-09-06 11:44 UTC
Hello, I've been following the protocol published on Nature and running `gffcompare` on two RNAseq replicates that I have. I removed the `-G` flag as (from what I understand) it's now the default behaviour.

Still, when I run
`gffcompare -r hg19.gtf merged.gtf`
I get the following error:
`Error allocating memory. Aborted (core dumped)`

When I run the tool in debugging mode with `-D` I see a lot of
`GFF Warning: unusual segment inclusion: exon(X-X) within CDS(X-X) (ID=X)`
and of
`GFF warning: merging adjacent/overlapping segments of X on X (X-X, X-X)`
and then:

```
Kept X ref transcripts out of Y
 W duplicate reference transcripts discarded.
Prefix for output files: gffcmp
Loading query file #1: merged.gtf
Error allocating memory.
Aborted (core dumped)
```

Any idea on what could be causing this?
I am working on an **Ubuntu 16.04** machine and I tried both with the precompiled binaries and with my own build (following instruction in the README file).

Many thanks in advance!
Cheers

**Comment by gpertea** [comment] 2016-09-06 14:34
Ouch, that should not happen (I assume you do have at least 6GB RAM on that machine) -- but before I build an Ubuntu VM for this I would like to see if I could reproduce that error on my system, and for that I have to know more about those input files you used; it looks like both the reference hg19.gtf and the merged.gtf file seem to have caused some issues with gffcompare. Not sure why you masked all those numbers and names there (X,Y,W), that makes me worry that you might not be able to share those two GTF files with me for debugging ?

Still I have to ask -- is there a chance you could share those GTFs with me for proper debugging? At least the reference hg19.gtf should be public, I assume (in which case maybe you can let me know where I could download exactly that file you used, unless it's a locally customized version of UCSC's hg19 annotation data?).

**Comment by ggirelli** [comment] 2016-09-06 15:05
Hej, thanks for the quick reply!

So, my machine has 32GB of RAM but the same happens on a 64GB RAM machine...
The hg19.gtf is obtained from UCSC Table Browser, I'll share it.
The merged.gtf file is obtained from public data so I can share that too, no problem :)
The masking is just a habit, sorry.

I'll mention, even if it's related to `stringtie` and not `gffcompare`, that I get the same error when running `stringtie -e -B -p 8 -G merged.gtf -o sample1.ballgown.gtf sample1.gtf`.

Here are the files: https://we.tl/10sXyEBjmo

Thanks! :D

**Comment by gpertea** [comment] 2016-09-06 21:44
Thank you very much for your help in tracking this issue down. I fixed the bug I had there in parsing some of those UCSC genes (duplicate gene_id were the culprit, found a workaround) and I updated gffcompare to version 0.9.8 to include these fixes and adding back support for the -G option (which is ignored actually, as it's the default, but at least it won't complain about it -- for people running it as described in the protocol paper). 

Please download the updated version and let me know if it fixes the problem for you. StringTie should also be recompiled with the new gclib code -- that's going to be done shortly.

**Comment by ggirelli** [comment] 2016-09-07 06:58
Thanks, that was fast! I just downloaded the new `gclib` version and built again both `stringtie` and `gffcompare`. Everything works smoothly now :)

**Closed** 2017-01-18 20:30 UTC

**Comment by yongjiam** [comment] 2022-11-30 02:55
Hi Gpertea,
I experienced the same issue whiling using gffread to extract cds and pep:
**gffread -g genome.fa -y pep.fa gene.gff
Error allocating memory.**

Do you think it may be caused by the same reason. I had no problem using other data, only came across this error with this data. Would you please advise me how to fix it? Something wrong with the gff file? Thanks.

Yong
